[package]
name = "find_cuda_helper"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Helper crate for searching for CUDA libraries"
repository = "https://github.com/Rust-GPU/Rust-CUDA"
readme = "../../README.md"

[dependencies]
glob = "0.3.0"
