[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
pico-args = "0.4.2"
rayon = "1.5.1"
regex = "1.3.9"
rustc_codegen_nvvm = { path = "../crates/rustc_codegen_nvvm" }
