[package]
name = "optix"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rust-GPU/Rust-CUDA"
readme = "../../README.md"

[dependencies]
optix_sys = { version = "0.1", path = "../optix_sys" }
cust = { version = "0.2", path = "../cust" }
